language: go

# `make ci` uses Docker.
sudo: required
services:
  - docker

# We can't test Go 1.5, because golint requires >1.6 (which is annoying).
# Also note that this probably doesn't work with `make ci` right now.
go:
  - 1.7
  #- 1.6
  #- master

before_install:
  - go get -u github.com/cpuguy83/go-md2man

env:
  - DOCKER_IMAGE="opensuse/amd64:42.2"
  - DOCKER_IMAGE="fedora:latest"
  - DOCKER_IMAGE="debian:jessie"
  - DOCKER_IMAGE="ubuntu:16.04"

notifications:
    email: false

script:
  - make umoci
  - make umoci.static
  - make DOCKER_IMAGE=$DOCKER_IMAGE ci
