language: go

# `make ci` uses Docker.
sudo: required
services:
  - docker

go:
  - 1.x

before_install:
  - go get -u github.com/cpuguy83/go-md2man
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/golang/lint/golint

env:
  - DOCKER_IMAGE="opensuse/amd64:42.2"
  - DOCKER_IMAGE="fedora:latest"
  - DOCKER_IMAGE="debian:jessie"
  - DOCKER_IMAGE="ubuntu:16.04"

notifications:
    email: false

script:
  - chmod a+rwx . # Necessary to make Travis co-operate with Docker.
  - make DOCKER_IMAGE=$DOCKER_IMAGE ci
